version: '3.8'

services:
  spark-master:
    image: bitnami/spark:3.4.1
    container_name: spark-master
    hostname: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_LOCAL_DIRS=/tmp
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=1G
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - spark-network

  spark-worker:
    image: bitnami/spark:3.4.1
    container_name: spark-worker
    hostname: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=1G
    ports:
      - "8081:8081"
    networks:
      - spark-network
    depends_on:
      - spark-master
    volumes:
      - .:/app
    working_dir: /app

  spark-submit:
    image: bitnami/spark:3.4.1
    container_name: spark-submit
    hostname: spark-submit
    environment:
      - SPARK_MODE=client
      - SPARK_MASTER_URL=spark://spark-master:7077
    networks:
      - spark-network
    depends_on:
      - spark-master
      - spark-worker
    volumes:
      - .:/app
    working_dir: /app

  pyspark:
    image: bitnami/spark:3.4.1
    container_name: pyspark
    hostname: pyspark
    environment:
      - SPARK_MODE=client
      - SPARK_MASTER_URL=spark://spark-master:7077
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - spark-network
    depends_on:
      - spark-master
      - spark-worker

  notebook:
    image: jupyter/all-spark-notebook
    ports:
      - "8888:8888"
    volumes:
      - .:/src
    working_dir: /src
    networks:
      - spark-network
    depends_on:
      - spark-master
      - spark-worker
      - spark-submit

networks:
  spark-network:
    driver: bridge