version: '3.8'

services:
  spark-master:
    image: bitnami/spark:3.5.1
    container_name: spark-master
    hostname: spark-master
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8080
      - SPARK_RPC_AUTHENTICATION_ENABLED=no
      - SPARK_RPC_ENCRYPTION_ENABLED=no
      - SPARK_SSL_ENABLED=no
      - SPARK_LOCAL_DIRS=/tmp
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=1G
      - BITNAMI_IMAGE_VERSION=11-debian-10-r202
      - PYSPARK_PYTHON=/usr/bin/python3.11
      - PYSPARK_DRIVER_PYTHON=/usr/bin/python3.11
    volumes:
      - .:/app
    ports:
      - "8080:8080"
      - "7077:7077"
    networks:
      - default_net

  spark-worker:
    image: bitnami/spark:3.5.1
    container_name: spark-worker
    hostname: spark-worker
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_WEBUI_PORT=8081
      - SPARK_WORKER_CORES=2
      - SPARK_WORKER_MEMORY=1G
      - BITNAMI_IMAGE_VERSION=11-debian-10-r202
    ports:
      - "8081:8081"
    depends_on:
      - spark-master
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - default_net

  spark-submit:
    image: bitnami/spark:3.5.1
    container_name: spark-submit
    hostname: spark-submit
    environment:
      - SPARK_MODE=client
      - SPARK_MASTER_URL=spark://spark-master:7077
      - BITNAMI_IMAGE_VERSION=11-debian-10-r202
    depends_on:
      - spark-master
      - spark-worker
    volumes:
      - .:/app
    working_dir: /app
    networks:
      - default_net

  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: airflow
      POSTGRES_PASSWORD: airflow
      POSTGRES_DB: airflow
    expose:
      - 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default_net

  webserver:
    build: .
    restart: always
    depends_on:
      - postgres
      - spark-master
    links:
      - spark-master
    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__WEBSERVER__SECRET_KEY: 'qwerty'
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ''
    ports:
      - "8085:8080"
    command: webserver
    networks:
      - default_net

  scheduler:
    build: .
    restart: always
    depends_on:
      - postgres
      - webserver
      - spark-master
    links:
      - spark-master
    environment:
      AIRFLOW__CORE__DAG_RUN_CONF_OVERRIDES_PARAMS: False
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
      AIRFLOW__CORE__FERNET_KEY: ''
      AIRFLOW__WEBSERVER__SECRET_KEY: 'qwerty'
    networks:
      - default_net
    volumes:
      - .:/app
#      - ./tasks:/opt/airflow/tasks  # See: airflow/airflow.cfg in apache/airflow
      - ./dags:/opt/airflow/dags  # See: airflow/airflow.cfg in apache/airflow
#      - ./file_storage/raw/:/home/airflow/raw/
#      - ./file_storage/processed/:/home/airflow/processed/
    command: scheduler
volumes:
  postgres_data:
networks:
    default_net: