### Trigger JOB 1
POST http://127.0.0.1:8081
Content-Type: application/json

{
  "date": "2022-08-09",
  "raw_dir": "raw/sales/2022-08-09"
}

### Trigger JOB 2
POST http://127.0.0.1:8082
Content-Type: application/json

{
  "raw_dir": "raw/sales/2022-08-09",
  "stg_dir": "stg/sales/2022-08-09"
}

###